/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SFaS.gui.AdminControl;

import SFaS.controller.AddAccountController;
import SFaS.controller.ConnectDB;
import SFaS.controller.DeleteAccountController;
import SFaS.controller.EditAccountController;
import SFaS.gui.*;
import SFaS.model.Account;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author kritiqual
 */
public class AccountControl extends javax.swing.JFrame {

    /**
     * Creates new form AccountControl
     */
    public AccountControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAccountControl = new javax.swing.JLabel();
        btnEditAccount = new javax.swing.JButton();
        btnDeleteAccount = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        labelUsernameAC = new javax.swing.JLabel();
        labelPasswordAC = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        labelAdminCb = new javax.swing.JLabel();
        cbAdmin = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAccountList = new javax.swing.JTable();
        btnAddAccount = new javax.swing.JButton();
        btnResetInfo = new javax.swing.JButton();
        tfPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAccountControl.setText("QUẢN LÝ TÀI KHOẢN");

        btnEditAccount.setText("EDIT");
        btnEditAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAccountActionPerformed(evt);
            }
        });

        btnDeleteAccount.setText("DELETE");
        btnDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccountActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        labelUsernameAC.setText("Username");

        labelPasswordAC.setText("Password");

        labelAdminCb.setText("Is Admin?");

        cbAdmin.setMaximumSize(new java.awt.Dimension(23, 25));
        cbAdmin.setMinimumSize(new java.awt.Dimension(23, 25));
        cbAdmin.setPreferredSize(new java.awt.Dimension(23, 25));

        tableAccountList.setBorder(new javax.swing.border.MatteBorder(null));
        tableAccountList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Is Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAccountList.getTableHeader().setReorderingAllowed(false);
        tableAccountList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAccountListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAccountList);
        if (tableAccountList.getColumnModel().getColumnCount() > 0) {
            tableAccountList.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        btnAddAccount.setText("ADD");
        btnAddAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAccountActionPerformed(evt);
            }
        });

        btnResetInfo.setText("RESET");
        btnResetInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(labelAccountControl)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelUsernameAC)
                                    .addComponent(labelPasswordAC))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelAdminCb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfPassword)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnEditAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(btnAddAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnResetInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeleteAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAccountControl)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelUsernameAC)
                                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelAdminCb))
                            .addComponent(cbAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPasswordAC)
                            .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddAccount)
                            .addComponent(btnDeleteAccount))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditAccount)
                            .addComponent(btnResetInfo)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new AdminUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAccountActionPerformed
        try {
            Connection conn = ConnectDB.getConnection();
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM Account");
            ResultSet rs = ps.executeQuery();
            String uncheck = String.valueOf(rs.getString("Username"));
            String pwcheck = String.valueOf(rs.getString("Password"));
            boolean iacheck = rs.getInt("AccType") == 1;

            String username = tfUsername.getText().trim();
            String password = tfPassword.getText().trim();
            int acctype = 0;
            if (cbAdmin.isSelected()) {
                acctype = 1;
            }
            boolean act = acctype == 0;

            Account acc = new Account(username, password, acctype);
            String edit = "UPDATE Account";
            if (!uncheck.equals(username)) {
                edit += " SET Username = ?";
            }
            if (!pwcheck.equals(password)) {
                edit += " SET Password = ?";
            }
            if (!iacheck == act) {
                edit += " SET AccType = ?";
            }

            JOptionPane.showMessageDialog(this.getContentPane(), EditAccountController.onEditEvent(acc, edit), "Thông báo!", JOptionPane.INFORMATION_MESSAGE);
            UpdateTable();
            this.dispose();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this.getContentPane(), e.getMessage(), "Thông Báo", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnEditAccountActionPerformed

    private void btnAddAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccountActionPerformed
        try {
            String username = tfUsername.getText().trim();
            String password = tfPassword.getText().trim();
            int acctype = 0;
            if (cbAdmin.isSelected()) {
                acctype = 1;
            }

            if ("".equals(username) || "".equals(password)) {
                throw new Exception("Không được để trống thông tin!");
            }

            JOptionPane.showMessageDialog(this.getContentPane(), AddAccountController.onSignupEvent(new Account(username, password, acctype)), "Thông báo!", JOptionPane.INFORMATION_MESSAGE);
            UpdateTable();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this.getContentPane(), e.getMessage(), "Thông Báo", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnAddAccountActionPerformed

    private void btnDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccountActionPerformed
        try {
            String username = tableAccountList.getModel().getValueAt(tableAccountList.getSelectedRow(), 0).toString();
            JOptionPane.showMessageDialog(this.getContentPane(), DeleteAccountController.onDeleteEvent(username), "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            UpdateTable();
            this.dispose();

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this.getContentPane(), e.getMessage(), "Thông Báo", JOptionPane.OK_OPTION);
        }

    }//GEN-LAST:event_btnDeleteAccountActionPerformed

    private void btnResetInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetInfoActionPerformed
        onClear();
    }//GEN-LAST:event_btnResetInfoActionPerformed

    private void tableAccountListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAccountListMouseClicked
        int selected = tableAccountList.getSelectedRow();
        TableModel model = tableAccountList.getModel();
        tfUsername.setText(model.getValueAt(selected, 0).toString());
        tfPassword.setText(model.getValueAt(selected, 1).toString());
        boolean checked = false;
        if ((boolean) model.getValueAt(selected, 2)) {
            checked = true;
        }
        cbAdmin.setSelected(checked);
    }//GEN-LAST:event_tableAccountListMouseClicked

    private void onClear() {
        tfUsername.setText("");
        tfPassword.setText("");
        cbAdmin.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    private static void UpdateTable() {
        new AccountControl().setVisible(true);
        try {
            Connection conn = ConnectDB.getConnection();
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM Account");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                String username = String.valueOf(rs.getString("Username"));
                String password = String.valueOf(rs.getString("Password"));
                boolean isAdmin = rs.getInt("AccType") == 1;

                Object tbdata[] = {username, password, isAdmin};
                DefaultTableModel tbModel = (DefaultTableModel) tableAccountList.getModel();
                tbModel.addRow(tbdata);
            }

            tableAccountList.setRowSelectionInterval(0, 0);
        } catch (SQLException ex) {
            Logger.getLogger(AccountControl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            UpdateTable();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAccount;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteAccount;
    private javax.swing.JButton btnEditAccount;
    private javax.swing.JButton btnResetInfo;
    private javax.swing.JCheckBox cbAdmin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAccountControl;
    private javax.swing.JLabel labelAdminCb;
    private javax.swing.JLabel labelPasswordAC;
    private javax.swing.JLabel labelUsernameAC;
    private static javax.swing.JTable tableAccountList;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
